site_name: Math
pages:
  - "Home": index.md
  - "Austria":
    - "National":
      - "2017": "austria/national/2017.md"
  - "Germany":
    - "National":
      - "2017": "germany/national/2017.md"
      - "2016": "germany/national/2016.md"
  - "Switzerland":
    - "National":
      - "2017": "switzerland/national/2017.md"

theme: 'material'
extra:
  palette:
    primary: 'teal'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'cloud'
  feature:
    tabs: true

extra_css:
  - css/style.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.arithmatex
